### ISSUE TITLE
Not an issue but suggestion

### ISSUE THREAD

**Issue by eligosoftware** [LorenRd/JetsonYolov4#2]
To run on Jetson Nano via CSI camera this script I found was very helpful:

./darknet detector demo cfg/obj.data cfg/yolov4-tiny/masks.cfg yolov4-tiny-obj_last.weights "nvarguscamerasrc ! video/x-raw(memory:NVMM), width=1920, height=1080, format=(string)NV12, framerate=(fraction)30/1 ! nvvidconv flip-method=2  ! video/x-raw, format=(string)BGRx ! videoconvert ! video/x-raw, format=(string)BGR ! appsink"

**Comment by LorenRd** [comment]
Thanks for the feedback!
